name: fates_for_quest
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  provider: ^6.0.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  hive_generator: ^1.1.2
  build_runner: ^2.1.8

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/d20.svg
